#CLASS
Name druid~
ShortName Dru~
PrimeStat wis
SchoolWeapon 3700
GuildRoom 3003
GuildRoom 3002
SkillAdept 75
Thac0_00 18
Thac0_32 2
HPRate 70
ManaRate 80
AddExp 100
StatMod 0 0 3 0 0 5
Skill 'acid blast' 63 1 0
Skill 'bury' 32 1 0
Skill 'mind light' 56 1 0
Skill 'aid' 53 1 0
Skill 'armor' 1 1 0
Skill 'blade barrier' 60 1 0
Skill 'bless' 14 1 0
Skill 'blindness' 14 1 0
Skill 'bluefire' 37 1 0
Skill 'call lightning' 28 1 0
Skill 'cause critical' 15 1 0
Skill 'cause light' 2 1 0
Skill 'cause serious' 8 1 0
Skill 'continual light' 5 1 0
Skill 'control weather' 21 1 0
Skill 'create food' 8 1 0
Skill 'create spring' 27 1 0
Skill 'create water' 3 1 0
Skill 'cure blindness' 11 1 0
Skill 'cure critical' 18 1 0
Skill 'cure disease' 19 1 0
Skill 'cure light' 4 1 0
Skill 'cure poison' 23 1 0
Skill 'cure serious' 10 1 0
Skill 'desert fist' 58 1 0
Skill 'detect evil' 11 1 0
Skill 'detect good' 11 1 0
Skill 'detect invis' 17 1 0
Skill 'detect magic' 12 1 0
Skill 'detect poison' 39 1 0
Skill 'dispel evil' 27 1 0
Skill 'dispel good' 27 1 0
Skill 'dispel magic' 43 1 0
Skill 'earthquake' 19 1 0
Skill 'energy drain' 42 1 0
Skill 'enhanced armor' 33 1 76
Skill 'faerie fire' 6 1 0
Skill 'faerie fog' 31 1 0
Skill 'fireproof' 16 1 0
Skill 'flamestrike' 42 1 0
Skill 'fly' 30 1 0
Skill 'floating disc' 10 1 0
Skill 'frenzy' 34 1 0
Skill 'gate' 63 1 0
Skill 'giant strength' 39 1 0
Skill 'group defense' 35 1 0
Skill 'group heal' 65 1 0
Skill 'harm' 26 1 0
Skill 'heal' 28 1 0
Skill 'heat metal' 21 1 0
Skill 'hurricane' 65 1 0
Skill 'identify' 36 1 0
Skill 'infravision' 25 1 0
Skill 'inspire' 49 1 0
Skill 'know alignment' 13 1 0
Skill 'locate object' 30 1 0
Skill 'mass healing' 54 1 0
Skill 'mass sanctuary' 62 1 0
Skill 'nexus' 55 1 0
Skill 'pass door' 32 1 0
Skill 'poison' 22 1 0
Skill 'polymorph' 43 1 0
Skill 'portal' 35 1 0
Skill 'protection cold' 44 1 0
Skill 'protection evil' 9 1 0
Skill 'protection good' 9 1 0
Skill 'protection heat' 39 1 0
Skill 'protective shield' 38 1 0
Skill 'refresh' 7 1 0
Skill 'remove curse' 32 1 0
Skill 'remove fear' 34 1 0
Skill 'restoring light' 71 1 0
Skill 'sanctuary' 29 1 0
Skill 'severity force' 45 1 0
Skill 'shield' 35 1 0
Skill 'slow' 38 1 0
Skill 'solar flight' 35 1 0
Skill 'stone skin' 33 1 0
Skill 'sulfurus spray' 28 1 0
Skill 'summon' 22 1 0
Skill 'word of recall' 28 1 0
Skill 'flail' 1 2 0
Skill 'mace' 1 2 0
Skill 'shield block' 17 1 -20
Skill 'whip' 1 2 0
Skill 'enhanced damage' 33 2 -20
Skill 'hand to hand' 30 1 0
Skill 'kick' 12 1 0
Skill 'parry' 25 1 0
Skill 'spell craft' 30 1 0
Skill 'second attack' 28 1 0
Skill 'fast healing' 9 1 0
Skill 'haggle' 18 2 0
Skill 'meditation' 6 1 0
Skill 'scrolls' 1 1 0
Skill 'staves' 1 1 0
Skill 'trance' 15 1 0
Skill 'wands' 1 1 0
Title 0 male the Man~
Title 0 female the Woman~
Title 1 male the Believer~
Title 1 female the Believer~
Title 2 male the Attendant~
Title 2 female the Attendant~
Title 3 male the Acolyte of the Wild~
Title 3 female the Acolyte of the Wild~
Title 4 male the Novice Druid~
Title 4 female the Novice Druid~
Title 5 male the Novice Druid~
Title 5 female the Novice Druid~
Title 6 male the Adept of the Wild~
Title 6 female the Adept of the Wild~
Title 7 male the Son of the Forest~
Title 7 female the Daughter of the Forest~
Title 8 male the Son of the Land~
Title 8 female the Daughter of the Land~
Title 9 male the Watcher of the Forest~
Title 9 female the Watcher of the Forest~
Title 10 male the Watcher of the Land~
Title 10 female the Watcher of the Land~
Title 11 male the Friend to the Animals~
Title 11 female the Friend to the Animals~
Title 12 male the Friend to the Animals~~
Title 12 female the Friend to the Animals~
Title 13 male the Guardian of the Animals~
Title 13 female the Guardian of the Animals~
Title 14 male the Guardian of the Animals~
Title 14 female the Guardian of the Animals~
Title 15 male the Priest of the Druidic Order~
Title 15 female the Priestess of the Druidic Order~
Title 16 male the Priest of the Druidic Order~
Title 16 female the Priestess of the Druidic Order~
Title 17 male the Sage of Natures Lore~
Title 17 female the Lady of Natures Lore~
Title 18 male the Sage of Natures Lore~
Title 18 female the Lady of Natures Lore~
Title 19 male the Champion of the Animals~
Title 19 female the Champion of the Animals~
Title 20 male the Champion of the Animals~
Title 20 female the Champion of the Animals~
Title 21 male the Champion of Life~
Title 21 female the Champion of Life~
Title 22 male the Champion of Life~
Title 22 female the Champion of Life~
Title 23 male the Healer of the Forest~
Title 23 female the Healer of the Forest~
Title 24 male the Healer of the Forest~
Title 24 female the Healer of the Forest~
Title 25 male the Healer of the Land~
Title 25 female the Healer of the Land~
Title 26 male the Healer of the Land~
Title 26 female the Healer of the Land~
Title 27 male the Wood Walker~
Title 27 female the Wood Walker~
Title 28 male the Wood Walker~
Title 28 female the Wood Walker~
Title 29 male the Priest of Nature~
Title 29 female the Priestess of Nature~
Title 30 male the Priest of Nature~
Title 30 female the Priestess of Nature~
Title 31 male the Elder Druid~
Title 31 female the Elder Druidess~
Title 32 male the Elder Druid~
Title 32 female the Elder Druidess~
Title 33 male the Woodland Caretaker~
Title 33 female the Woodland Caretaker~
Title 34 male the Woodland Caretaker~
Title 34 female the Woodland Caretaker~
Title 35 male the Woodland Caretaker~
Title 35 female the Woodland Caretaker~
Title 36 male the Woodland Caretaker~
Title 36 female the Woodland Caretaker~
Title 37 male the Arch Druid~
Title 37 female the Arch Druidess~
Title 38 male the Arch Druid Sage~
Title 38 female the Arch Druidess Sage~
Title 39 male the Arch Druid Sage~
Title 39 female the Arch Druidess Sage~
Title 40 male the Forest Watcher~
Title 40 female the Forest Watcher~
Title 41 male the Forest Watcher~
Title 41 female the Forest Watcher~
Title 42 male the Forest Guardian~
Title 42 female the Forest Guardian~
Title 43 male the Forest Guardian~
Title 43 female the Forest Guardian~
Title 44 male the Elder Druid~
Title 44 female the Elder Druidess~
Title 45 male the Elder Druid~
Title 45 female the Elder Druidess~
Title 46 male the Hallowed Druid~
Title 46 female the Hallowed Druidess~
Title 47 male the Hallowed Druid~
Title 47 female the Hallowed Druidess~
Title 48 male the Protector of Fire~
Title 48 female the Protector of Fire~
Title 49 male the Protector of Fire~
Title 49 female the Protector of Fire~
Title 50 male the Protector of Earth~
Title 50 female the Protector of Earth~
Title 51 male the Protector of Earth~
Title 51 female the Protector of Earth~
Title 52 male the Protector of Water~
Title 52 female the Protector of Water~
Title 53 male the Protector of Water~
Title 53 female the Protector of Water~
Title 54 male the Protector of Air~
Title 54 female the Protector of Air~
Title 55 male the Protector of Air~
Title 55 female the Protector of Air~
Title 56 male the Revered Druid~
Title 56 female the Revered Druidess~
Title 57 male the Revered Druid~
Title 57 female the Revered Druidess~
Title 58 male the Elemental Watcher~
Title 58 female the Elemental Watcher~
Title 59 male the Elemental Watcher~
Title 59 female the Elemental Watcher~
Title 60 male the Druid of Autumn~
Title 60 female the Druidess of Autumn~
Title 61 male the Druid of Autumn~
Title 61 female the Druidess of Autumn~
Title 62 male the Druid of Winter~
Title 62 female the Druidess of Winter~
Title 63 male the Druid of Winter~
Title 63 female the Druidess of Winter~
Title 64 male the Druid of Spring~
Title 64 female the Druidess of Spring~
Title 65 male the Druid of Spring~
Title 65 female the Druidess of Spring~
Title 66 male the Druid of Summer~
Title 66 female the Druidess of Summer~
Title 67 male the Druid of Summer~
Title 67 female the Druidess of Summer~
Title 68 male the Druid of the Winds~
Title 68 female the Druidess of the Winds~
Title 69 male the Weaver of Storms~
Title 69 female the Weaver of Storms~
Title 70 male the Weaver of Storms~
Title 70 female the Weaver of Storms~
Title 71 male the Guardian of the Animals~
Title 71 female the Guardian of the Animals~
Title 72 male the Guardian of the Animals~
Title 72 female the Guardian of the Animals~
Title 73 male the Grand Druid~
Title 73 female the Grand Druidess~
Title 74 male the Grand Druid~
Title 74 female the Grand Druidess~
Title 75 male the Savant of Fire~
Title 75 female the Savanti of Fire~
Title 76 male the Savant of Fire~
Title 76 female the Savanti of Fire~
Title 77 male the Savant of Earth~
Title 77 female the Savanti of Earth~
Title 78 male the Savant of Earth~
Title 78 female the Savanti of Earth~
Title 79 male the Savant of Water~
Title 79 female the Savanti of Water~
Title 80 male the Savant of Water~
Title 80 female the Savanti of Water~
Title 81 male the Savant of Air~
Title 81 female the Savanti of Air~
Title 82 male the Savant of Air~
Title 82 female the Savanti of Air~
Title 83 male the Lord of the River~
Title 83 female the Lady of the River~
Title 84 male the Lord of the River~
Title 84 female the Lady of the River~
Title 85 male the Master of the Four Seasons~
Title 85 female the Mistress of the Four Seasons~
Title 86 male the Master of the Four Seasons~
Title 86 female the Mistress of the Four Seasons~
Title 87 male the Master of the Elements~
Title 87 female the Mistress of the Elements~
Title 88 male the Master of the Elements~
Title 88 female the Mistress of the Elements~
Title 89 male the Master of Storms~
Title 89 female the Mistress of Storms~
Title 90 male the Immaculate Druid~
Title 90 female the Immaculate Druidess~
Title 91 male the Hand of Nature~
Title 91 female the Hand of Nature~
Title 92 male the Avatar of Nature~
Title 92 female the Avatar of Nature~
Title 93 male the Savior of Nature~
Title 93 female the Savior of Nature~
Title 94 male the Demigod~
Title 94 female the Demigoddess~
Title 95 male the Immortal~
Title 95 female the Immortal~
Title 96 male the Elemental God~
Title 96 female the Elemental Goddess~
Title 97 male the Deity~
Title 97 female the Deity~
Title 98 male the Supreme Master~
Title 98 female the Supreme Mistress~
Title 99 male the Creator~
Title 99 female the Creator~
Title 100 male the Implementor~
Title 100 female the Implementress~
End


#$
